name: ElementSwap
author: vincentbluff
category: Utilities
tags: [element]
current: 1.0.1
docs: http://github.com/vincentbluff/ElementSwap/blob/master/README.md
demo: http://vincentbluff.github.com/ElementSwap